### ISSUE TITLE
mem_parse UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by alisheikholeslam** [pra-dan/TAMPPA#2] opened 2022-01-09 09:24 UTC
I would like to use TAMPPA for the [following line_profiler code](https://stackoverflow.com/a/43377717/13394817) and **_in coding body, not in console_** or …:
```
from line_profiler import LineProfiler

lp = LineProfiler()
lp.add_function(inbox_)
lp.add_function(operation_)
lp_wrapper = lp(elapses)
lp_wrapper(r, pos, gap, ends_ind, elem_vert, contact_poss)
lp.print_stats()
```
It shows the results [on the Colab](https://colab.research.google.com/drive/1yL6vdPSnx_NQQ9-eRFQ9u4TkPWHbwZXK?usp=sharing). For using TAMPPA, after dumping a txt file by:
```
lp.dump_stats("mem_res_1.txt")
```
I have used TAMPPA as:
```
from tamppa import mem_parse
mem_parse("/content/mem_res_1.txt")
```
It gets an error on Google Colab:

> UnicodeDecodeError                        Traceback (most recent call last)
> <ipython-input-30-367ce544c5f4> in <module>()
>       1 from tamppa import mem_parse
> ----> 2 mem_parse("/content/mem_res_1.txt")
> 
> 2 frames
> /usr/lib/python3.7/codecs.py in decode(self, input, final)
>     320         # decode input (taking the buffer into account)
>     321         data = self.buffer + input
> --> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
>     323         # keep undecoded input until the next call
>     324         self.buffer = data[consumed:]
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I would be appreciated if you would guide me to solve the error.

best regards,
Ali

**Comment by pra-dan** [comment] 2022-01-09 12:59
Hi Ali, I tried to reproduce your error using 
```python3
from line_profiler import LineProfiler
import random

def do_stuff(numbers):
    s = sum(numbers)
    l = [numbers[i]/43 for i in range(len(numbers))]
    m = ['hello'+str(numbers[i]) for i in range(len(numbers))]

numbers = [random.randint(1,100) for i in range(1000)]
lp = LineProfiler()
lp_wrapper = lp(do_stuff)
lp_wrapper(numbers)
lp.print_stats()
lp.dump_stats("mem_res_1.txt")
```
On looking into the dumped logs, I see the cause of error
```console
cat mem_res_1.txt 
����line_profiler._line_profiler��	LineStats���)��}�(�timings�}��temp.py�Kdo_stuff���]�(KKK
```
On running TAMPPA on it, leads to the same error as yours. Whereas, on saving the logs into a file using the console method, gives the expected results. 

Can you check the log `txt` file ?

**Comment by alisheikholeslam** [comment] 2022-01-09 15:52
I didn't understand why? Do I have to use it just by console?. The [mem_res_1.txt](https://github.com/pra-dan/TAMPPA/files/7835369/mem_res_1.txt) is:

![error](https://user-images.githubusercontent.com/63285654/148689773-1766da31-3991-40d3-b11e-00060ffd54f6.PNG)

**Comment by pra-dan** [comment] 2022-01-09 16:48
I guess you will need to look further into `lp.dump_stats()` and maybe
official docs of line_profiler may help here.

**Comment by alisheikholeslam** [comment] 2022-01-09 17:37
The exported file is in binary mode. I guess it is related to this. So, the file must be prepared for UTF-8 to be readable by `mem_parse`. I don't know if `lp.dump_stats()` could handle it. As I know, it get just filename as the argument, not the exporting format.

**Comment by pra-dan** [comment] 2022-01-10 12:37
I looked into the [source of `dump_stats`](https://github.com/pyutils/line_profiler/blob/5994c08bec2e4845a2b74d6c5f2d5c9b526f696f/line_profiler/line_profiler.py#L99) but nothing of help there. Maybe you can submit an issue there for lack of documentation regarding dumped stat format.

**Comment by alisheikholeslam** [comment] 2022-01-10 13:05
Is the desired saved text output format put somewhere to see its output format. If no, I would be appreciated if you would attach your outputted _mem_res_1.txt_ (which you get using the console method) for the above example here.
Thanks.

**Comment by pra-dan** [comment] 2022-01-10 14:53
You can run the following (slightly modified code) to log onto the console, 
```python3 
from line_profiler import LineProfiler
import random

def do_stuff(numbers):
    s = sum(numbers)
    l = [numbers[i]/43 for i in range(len(numbers))]
    m = ['hello'+str(numbers[i]) for i in range(len(numbers))]

numbers = [random.randint(1,100) for i in range(1000)]
lp = LineProfiler()
lp_wrapper = lp(do_stuff)
lp_wrapper(numbers)
lp.print_stats()
#lp.dump_stats("mem_res_1.txt")
```
and run the file using `python3 file.py > mem_res_1.txt`. This way the stats/`stdout` [is redirected](https://askubuntu.com/a/420983/1044864) into the txt file instead of the console

**Comment by pra-dan** [comment] 2022-01-17 04:44
Hi @alisheikholeslam Is the issue resolved ? I assume its an issue with the `dump_stats` utility of `line_profiler`. Should I close this issue ?

**Comment by alisheikholeslam** [comment] 2022-01-17 09:23
Hi,

I checked again. As you are mentioning, It seems `line_profiler` uses a self-made template for `dump_stats`. I will express the solution, If I figure out something.

Do whatever you deem appropriate.

Best regards,
Ali

**Comment by pra-dan** [comment] 2022-01-17 17:23
I advise you interact the dev of `line_profiler` and maybe open an issue there.

Best of luck.

**Closed as completed by pra-dan** 2022-01-17 17:23 UTC

**Comment by alisheikholeslam** [comment] 2022-01-20 18:24
@pra-dan I have opened an issue there, want to inform if you would contribute. I did not satisfied by the answers there, yet, and could not understand what to do.

**Comment by alisheikholeslam** [comment] 2022-01-24 21:43
> I advise you interact the dev of `line_profiler` and maybe open an issue there.

@pra-dan Thanks for the presented solution on line_profiler#117.
I have a problem showing the results on my aforementioned [Colab link](https://colab.research.google.com/drive/1yL6vdPSnx_NQQ9-eRFQ9u4TkPWHbwZXK?usp=sharing).
As it is shown on the resulted image, the lines are weird and is not true.
I have tested it by using `subprocess.getoutput("python -m memory_profiler test.py > mem_res.txt")`, too. It gets same result, but in two outputted images:
![image](https://user-images.githubusercontent.com/63285654/150868718-75cff559-ba42-40a9-ad35-27b3fe438fb5.png)
**Do you have any idea why the line numbers are weird?**
I have some guesses on it:
1) sorting behavior in [line_profiler](https://github.com/pyutils/line_profiler/blob/5994c08bec2e4845a2b74d6c5f2d5c9b526f696f/line_profiler/line_profiler.py#L242)
2) functions' defining style on my python written code
